In [581]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


df=pd.read_csv("/content/sample_data/weatherAUS_train.csv")
df_ = pd.read_csv("/content/sample_data/weatherAUS_test.csv")

df_['RainToday'] = df_['RainToday'].map({'Yes': 1, 'No': 0})
df['RainToday'] = df['RainToday'].map({'Yes': 1, 'No': 0})

y = df["RainTomorrow"]
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2013-07-22,Sydney,8.7,17.2,0.0,3.8,9.9,WNW,54.0,WNW,W,17.0,26.0,54.0,28.0,1019.4,1016.3,2.0,2.0,12.2,16.6,0.0,0
1,2015-02-28,Sale,15.4,25.7,0.0,NaN,NaN,W,67.0,NNE,WSW,11.0,9.0,84.0,66.0,1008.1,1005.1,8.0,8.0,18.8,24.3,0.0,1
2,2009-11-18,PerthAirport,15.2,22.2,7.2,5.2,3.3,NW,78.0,NW,WSW,33.0,28.0,68.0,91.0,1001.5,1000.1,7.0,8.0,20.1,16.5,1.0,1
3,2014-02-19,Richmond,19.9,26.4,0.0,2.8,NaN,SW,24.0,NNE,WSW,13.0,9.0,97.0,97.0,1004.6,1002.1,NaN,NaN,22.6,22.3,0.0,1
4,2015-10-04,Wollongong,19.3,32.9,0.0,NaN,NaN,W,48.0,NNW,W,19.0,22.0,46.0,15.0,1022.8,1020.7,NaN,NaN,22.1,32.6,0.0,0

In [582]:
df_.shape

(28417, 23)

In [583]:
pd.set_option('display.max_columns', None)
df.columns

Index(['Date', 'Location', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation',
       'Sunshine', 'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [584]:

numeric_data = list(df.dtypes[df.dtypes == "float64"].index)
categorical = list(df.dtypes[df.dtypes == "object"].index)
df = pd.concat([df[numeric_data],
                     pd.get_dummies(df.Location),
                     pd.get_dummies(df.WindGustDir),
                     pd.get_dummies(df.WindDir9am),
                     pd.get_dummies(df.WindDir3pm)], axis=1)
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,Adelaide,Albany,Albury,AliceSprings,BadgerysCreek,Ballarat,Bendigo,Brisbane,Cairns,Canberra,Cobar,CoffsHarbour,Dartmoor,Darwin,GoldCoast,Hobart,Katherine,Launceston,Melbourne,MelbourneAirport,Mildura,Moree,MountGambier,MountGinini,Newcastle,Nhil,NorahHead,NorfolkIsland,Nuriootpa,PearceRAAF,Penrith,Perth,PerthAirport,Portland,Richmond,Sale,SalmonGums,Sydney,SydneyAirport,Townsville,Tuggeranong,Uluru,WaggaWagga,Walpole,Watsonia,Williamtown,Witchcliffe,Wollongong,Woomera,E,ENE,ESE,N,NE,NNE,NNW,NW,S,SE,SSE,SSW,SW,W,WNW,WSW,E,ENE,ESE,N,NE,NNE,NNW,NW,S,SE,SSE,SSW,SW,W,WNW,WSW,E,ENE,ESE,N,NE,NNE,NNW,NW,S,SE,SSE,SSW,SW,W,WNW,WSW
0,8.7,17.2,0.0,3.8,9.9,54.0,17.0,26.0,54.0,28.0,1019.4,1016.3,2.0,2.0,12.2,16.6,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1,15.4,25.7,0.0,NaN,NaN,67.0,11.0,9.0,84.0,66.0,1008.1,1005.1,8.0,8.0,18.8,24.3,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,15.2,22.2,7.2,5.2,3.3,78.0,33.0,28.0,68.0,91.0,1001.5,1000.1,7.0,8.0,20.1,16.5,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,19.9,26.4,0.0,2.8,NaN,24.0,13.0,9.0,97.0,97.0,1004.6,1002.1,NaN,NaN,22.6,22.3,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,19.3,32.9,0.0,NaN,NaN,48.0,19.0,22.0,46.0,15.0,1022.8,1020.7,NaN,NaN,22.1,32.6,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [585]:
df["RainTomorrow"] = y
df.isnull().sum()

MinTemp          1027
MaxTemp           875
Rainfall         2300
Evaporation     43889
Sunshine        48800
                ...
SW                  0
W                   0
WNW                 0
WSW                 0
RainTomorrow        0
Length: 115, dtype: int64

In [605]:
from sklearn.model_selection import train_test_split

numeric_data = df.select_dtypes([np.number])
numeric_data = numeric_data.drop('RainTomorrow', axis=1)
Y=df["RainTomorrow"]
X=df.drop(columns=["RainTomorrow"])

##X.insert(1, "Bias", np.ones((len(X), 1)), True)

X_train , X_test, Y_train, Y_test =  train_test_split(X, Y, test_size=0.4, random_state=42)


numeric_data_med = numeric_data.median()
numeric_features = numeric_data.columns

X_train = X_train.fillna(numeric_data_med)

X_test = X_test.fillna(numeric_data_med)

#categorical = list(X_train.dtypes[X_train.dtypes == "object"].index)

## X = np.hstack([X, np.ones((len(X), 1))])
X_train.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,Adelaide,Albany,Albury,AliceSprings,BadgerysCreek,Ballarat,Bendigo,Brisbane,Cairns,Canberra,Cobar,CoffsHarbour,Dartmoor,Darwin,GoldCoast,Hobart,Katherine,Launceston,Melbourne,MelbourneAirport,Mildura,Moree,MountGambier,MountGinini,Newcastle,Nhil,NorahHead,NorfolkIsland,Nuriootpa,PearceRAAF,Penrith,Perth,PerthAirport,Portland,Richmond,Sale,SalmonGums,Sydney,SydneyAirport,Townsville,Tuggeranong,Uluru,WaggaWagga,Walpole,Watsonia,Williamtown,Witchcliffe,Wollongong,Woomera,E,ENE,ESE,N,NE,NNE,NNW,NW,S,SE,SSE,SSW,SW,W,WNW,WSW,E,ENE,ESE,N,NE,NNE,NNW,NW,S,SE,SSE,SSW,SW,W,WNW,WSW,E,ENE,ESE,N,NE,NNE,NNW,NW,S,SE,SSE,SSW,SW,W,WNW,WSW
729,9.2,21.3,0.0,5.2,4.2,30.0,6.0,13.0,89.0,60.0,1011.5,1010.4,5.0,7.0,15.8,20.7,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
74578,13.6,28.8,0.0,4.8,8.4,33.0,24.0,20.0,42.0,21.0,1022.0,1017.4,5.0,1.0,19.9,28.2,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4775,10.9,19.1,0.0,1.4,9.2,70.0,28.0,31.0,79.0,59.0,1022.5,1017.9,1.0,2.0,13.7,18.7,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
98709,17.1,31.0,0.0,11.4,13.2,37.0,9.0,17.0,45.0,38.0,1013.2,1013.2,0.0,0.0,26.9,28.3,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
88580,11.3,16.4,0.0,11.0,6.1,65.0,24.0,20.0,47.0,44.0,1020.6,1021.8,3.0,7.0,13.2,14.7,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

Normalization

In [606]:
scaler = StandardScaler(copy = False)
X_train_scaled = scaler.fit(X_train[numeric_features])
X_test_scaled = scaler.transform(X_test[numeric_features])

AttributeError: 'StandardScaler' object has no attribute 'shape'

We made normal data, then we can work with it

In [610]:

#instantiate the model
logreg = LogisticRegression(solver='liblinear', random_state=0)


# fit the model
logreg.fit(X_train, Y_train)
#prediction
y_pred_test = logreg.predict(X_test)

y_pred_test
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(Y_test, y_pred_test)))

Model accuracy score: 0.8471

In [589]:
df.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm',
       ...
       'NW', 'S', 'SE', 'SSE', 'SSW', 'SW', 'W', 'WNW', 'WSW', 'RainTomorrow'],
      dtype='object', length=115)

In [590]:
X_train.Evaporation = X_train.Evaporation.clip(0, 24)
X_train.WindSpeed3pm = X_train.WindSpeed3pm.clip(0, 70)

In [591]:

#instantiate the model
logreg = LogisticRegression(solver='liblinear', random_state=0)


# fit the model
logreg.fit(X_train, Y_train)
#prediction
y_pred_test = logreg.predict(X_test)

y_pred_test
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(Y_test, y_pred_test)))

Model accuracy score: 0.8472

In [592]:
df_.shape

(28417, 23)

In [593]:
numeric_data = list(df_.dtypes[df_.dtypes == "float64"].index)
df_ = pd.concat([df_[numeric_data],
                     pd.get_dummies(df_.Location),
                     pd.get_dummies(df_.WindGustDir),
                     pd.get_dummies(df_.WindDir9am),
                     pd.get_dummies(df_.WindDir3pm)], axis=1)
df_.shape

(28417, 114)

In [594]:
numeric_data = df_.select_dtypes([np.number])
numeric_data_med = numeric_data.median()
numeric_features = numeric_data.columns

In [602]:
df_ = df_.fillna(numeric_data_med)
df_scaled = scaler.transform(df_[numeric_features])
df_.shape

(28417, 114)

In [603]:
df_scaled.shape

(28417, 210)

In [597]:
y = logreg.predict(df_)
y

array([0, 0, 0, ..., 0, 0, 0])

In [598]:
df1 = pd.DataFrame(y)
df1["Id"] = df1.index
df1.rename(columns={ 0: "RainTomorrow"},inplace=True)
#df1=df1.reindex(['Id','RainTomorrow'])
df1.to_csv('result2.csv', index = False)

In [599]:
df1.shape

(28417, 2)